default_language_version:
  python: python3.6

repos:

# black
- repo: https://github.com/ambv/black
  rev: 19.10b0
  hooks:
  - id: black
    exclude: __openerp__.py|__manifest__.py|odoo/external-src/

# pylint
- repo: https://github.com/pycqa/pylint
  rev: pylint-2.5.3
  hooks:
  - id: pylint
    name: pylint odoo
    # check only specific Odoo addons
    files: odoo/local-src/
    types: ['file', 'python']   # to not check .csv and .conf files
    args: ["--rcfile=pylintrc_odoo", "--valid_odoo_versions=14.0"]
    additional_dependencies: [pylint-odoo]
  - id: pylint
    name: pylint misc
    # check all Python code excepting Odoo addons
    exclude: odoo/local-src/|odoo/external-src/
    args: ["--rcfile=pylintrc"]

# flake8
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.8.3
  hooks:
    - id: flake8
      name: flake8 except __init__.py
      args: [--exclude=__init__.py]
      exclude: odoo/external-src/
      language_version: python3
      additional_dependencies: ["flake8-bugbear"]
    - id: flake8
      name: flake8 only __init__.py
      args: [--extend-ignore=F401]  # ignore imported unused in __init__.py
      files: __init__.py
      exclude: odoo/external-src/
      additional_dependencies: ["flake8-bugbear"]

# trailing whitespaces, yaml, flake8...
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.4.0
  hooks:
  - id: trailing-whitespace
    exclude: odoo/patches/|odoo/external-src/
  - id: end-of-file-fixer
    exclude: odoo/patches/|odoo/external-src/
  - id: check-yaml
    files: odoo/migration.yml
  - id: debug-statements
    exclude: odoo/external-src/

# pyupgrade
- repo: https://github.com/asottile/pyupgrade
  rev: v1.12.0
  hooks:
  - id: pyupgrade
    exclude: odoo/external-src/

# isort
- repo: https://github.com/pre-commit/mirrors-isort
  rev: v4.3.4
  hooks:
  - id: isort
    exclude: odoo/external-src/
